// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLEdjR1F_eJx_dJrCl4kjdiNdSJPK5r8c',
    appId: '1:260891614533:web:cc84f240039762f208722c',
    messagingSenderId: '260891614533',
    projectId: 'fcm-activity-ae7b1',
    authDomain: 'fcm-activity-ae7b1.firebaseapp.com',
    storageBucket: 'fcm-activity-ae7b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHepIS1dyXSfVaelkUinqZD3qnUk-OXg',
    appId: '1:260891614533:android:8a35bb2838387c8f08722c',
    messagingSenderId: '260891614533',
    projectId: 'fcm-activity-ae7b1',
    storageBucket: 'fcm-activity-ae7b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzNOxcq-ju_m6q5-iqIt1DOK02Bd-aPaQ',
    appId: '1:260891614533:ios:f7eb8a32ab3eff4208722c',
    messagingSenderId: '260891614533',
    projectId: 'fcm-activity-ae7b1',
    storageBucket: 'fcm-activity-ae7b1.firebasestorage.app',
    iosBundleId: 'com.example.fcmActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzNOxcq-ju_m6q5-iqIt1DOK02Bd-aPaQ',
    appId: '1:260891614533:ios:f7eb8a32ab3eff4208722c',
    messagingSenderId: '260891614533',
    projectId: 'fcm-activity-ae7b1',
    storageBucket: 'fcm-activity-ae7b1.firebasestorage.app',
    iosBundleId: 'com.example.fcmActivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLEdjR1F_eJx_dJrCl4kjdiNdSJPK5r8c',
    appId: '1:260891614533:web:1844f80aefdbd5fd08722c',
    messagingSenderId: '260891614533',
    projectId: 'fcm-activity-ae7b1',
    authDomain: 'fcm-activity-ae7b1.firebaseapp.com',
    storageBucket: 'fcm-activity-ae7b1.firebasestorage.app',
  );
}
